title: Dr. Arnab Mukherjee
logo: /assets/img/headshot.png
description: Neurology-focused physicianâ€“researcher integrating clinical neuroscience with Python-driven data analysis and large language models to advance AI-enabled neuroclinical research.
show_downloads: False
theme: jekyll-theme-minimal
